= Kernel Builder v2
Curt Brune <curt@enfabrica.net>

This is a new take on building kernel artifacts for astore.

This directory contains a set of helper scripts for building and
publishing kernel artifacts to astore.

See the script `sample-runner.sh` for an example of how to run the
scripts in sequence.

== `build.sh`

This script compiles a specific ENF Linux kernel branch and generates
Debian .deb files for all specified flavours.

A kernel flavour is a particular kernel configuration for an
architecture.  Currently two flavours are supported for amd64:

- generic -- This is a full kernel configuration, suitable for
  installing a real metal server.
- minimal -- This is a small configuration, suitable for a virtual
  machine install.

== `repo.sh`

This script creates a portable Debian APT repository for each kernel
flavour.  This APT repo contains all the .deb files generated by
`build.sh`.

== `make-archive.sh`

This script creates a bazel ready tarball of the Debian APT repository
for each flavour.  This tarball also includes an `install` script that
bazel executes when unpacking the tarball.

The install script takes the following arguments:
```
    -b Install for building kernel modules with Bazel
    -c Output APT sources.list.d config, but do not install
    -a Install APT sources.list.d config
```

The default without any arguments is the `-b` option, install for
building kernel modules with Bazel.

== `upload.sh`

This script uploads the bazel ready tarballs to astore.

== Install Kernel Packages via APT

The archive created by this build process can be used to install
kernel packages via apt.  To setup the apt repo on a host (either real
hardware or virtual) do this:

- download the kernel-artifacts.tar.gz from astore
- untar the archive where you want the repo to live (maybe /usr/local/share/enf/kernel-repo)
- using `sudo` run the install script with the `-a` option

```
$ cd /tmp
$ enkit astore get -a amd64 -u 8hauaw46d77kk2ixxh4i7r5evkr6oi28 kernel/enf/impish-19.19/minimal/kernel-artifacts.tar.gz
$ sudo mkdir /usr/share/enf/kernel-minimal-repo
$ cd /usr/share/enf/kernel-minimal-repo
$ sudo tar xf /tmp/kernel-artifacts.tar.gz
$ sudo ./install-5.13.0-19-1-1638665569-ga3b7c71b84a3-minimal.sh -a
$ sudo apt update
$ sudo apt install linux-image-5.13.0-19-1-1638665569-ga3b7c71b84a3-minimal
```
