= Kernel Builder v2
Curt Brune <curt@enfabrica.net>

This is a new take on building kernel artifacts for astore.

This directory contains a set of helper scripts for building and
publishing kernel artifacts to astore.

See the script `sample-runner.sh` for an example of how to run the
scripts in sequence.

== `build.sh`

This script compiles a specific ENF Linux kernel branch and generates
Debian .deb files for all specified flavours.

A kernel flavour is a particular kernel configuration for an
architecture.  Currently two flavours are supported for amd64:

- generic -- This is a full kernel configuration, suitable for
  installing a real metal server.
- minimal -- This is a small configuration, suitable for a virtual
  machine install.

== `repo.sh`

This script creates a portable Debian APT repository for each kernel
flavour.  This APT repo contains all the .deb files generated by
`build.sh`.

== `archive-bazel.sh`

This script creates a bazel ready tarball of kernel header files for
building kernel modules for each flavour.  This tarball also includes
an `install` script that bazel executes when unpacking the tarball.

== `archive-deb.sh`

This script creates a tarball of a Debian APT repo containing
kernel .deb packages for each flavour.  This repo can be used to
provision real hardware machines or virtual machines.

The install script requires one of the following arguments:
```
    -c Output APT sources.list.d config, but do not install
    -a Install APT sources.list.d config
```

== `upload.sh`

This script uploads the tarballs to astore.

For the bazel header file tarball, the URL is marked as "public",
because bazel requires that.

The URL for the Debian APT repo archive is marked as private in
astore.

== Install Kernel Packages via APT

The Debian archive created by this build process can be used to
install kernel packages via apt.  To setup the apt repo on a host
(either real hardware or virtual) do this:

- download the deb-artifacts.tar.gz from astore
- untar the archive where you want the repo to live (maybe /usr/local/share/enf/kernel-repo)
- using `sudo` run the install script with the `-a` option

```
$ cd /tmp
$ enkit astore get -a amd64 -u ch3in78s6hkep6a4gfpqwcxn2eo7b32y kernel/enf/impish-19.19/minimal/deb-artifacts.tar.gz
$ sudo mkdir /usr/share/enf/kernel-minimal-repo
$ cd /usr/share/enf/kernel-minimal-repo
$ sudo tar xf /tmp/kernel-artifacts.tar.gz
$ sudo ./install-5.13.0-19-1-1638919542-gc2095c9d9a38-minimal.sh -a
$ sudo apt update
$ sudo apt install linux-image-5.13.0-19-1-1638919542-gc2095c9d9a38-minimal
```
