= Kernel Builder and Publisher
Curt Brune <curt@enfabrica.net>

This directory contains one main driver script, `kpub-astore`, and a
set of helper scripts for building and publishing kernel artifacts to
astore.

== TL;DR -- Building For Production

Current as of 05/16/2022:

To publish the kernel artifacts, run `kpub-astore` like this:

  $ kpub-astore -b enf/impish-19.19 -l ENF_UBUNTU_IMPISH -a kernel

The `-b` option specifies the git branch in the kernel tree. Here we
are using `enf/impish-19.19`.

The `-l` option specifies the Bazel kernel label, which is used to
form various Bazel variables.  Here we are using `ENF_UBUNTU_IMPISH`.

The `-a` option specifies the root path in astore.  For a kernel
flavour, the artifacts are published to
`<astore_root>/<git-branch>/<flavour>`.  Here we are using the
production path `kernel`, which will publish artifacts to the
following paths:

  kernel/enf/impish-19.19/generic  (Ubuntu generic)

The build outputs a Bazel file, suitable for checking into the
internal repo in `bazel/kernel.version.bzl`.

See `kpub-astore -h` for more options to control the build.

== Build Time Dependencies

Building all the kernel Debian packages requires a number of
development packages to be installed on the build host.  The following
needs to be installed:

  $ sudo apt install \
            build-essential  \
            kernel-wedge     \
            grep-dctrl       \
            flex             \
            bison            \
            libudev-dev      \
            libusb-dev       \
            fakeroot         \
            libpci-dev       \
            libssl-dev       \
            libelf-dev       \
            libiberty-dev    \
            libcap-dev       \
            python3-docutils \
            asciidoc         \
            jq               \
            zstd

== The Inputs

The inputs to `kpub-astore` are:

- A git repo for the Enfabrica kernel.  It is expected that the kernel
  tree contains the top level `enfabrica` directory.  The Enfabrica
  github kernel repo is used by default.

- A git branch to check out and build.

- A list of Ubuntu-style kernel flavours to build.

- A scratch directory to use for downloading and building.

- A root URL within astore, where to publish the artifacts.

By design, the defaults for the build directory and astore directory
are scoped to the current `$USER` so as not to mess up production
locations.

See the online help, `kpub-astore -h`, for details on specifying the
inputs.

== The Outputs

The `kpub-astore` script publishes a number of kernel artifacts to astore.

=== Bazel Kernel Module Build Tarballs

This is a tarball of bazel build time files, including kernel header
files and module symbols.  This is used to build kernel modules from
within bazel.

This tarball includes an `install` script that bazel executes when
unpacking the tarball.

The script publishes a separate tarball for each kernel flavour.

=== Debian APT Repo Tarballs

This is a tarball of a Debian APT repo containing all the kernel .deb
packages for each flavour.  This repo can be used to provision real
hardware machines or virtual machines.

To install the APT repo on a machine, unpack the tarball and run the
install script inside.  The install script requires one of the
following arguments:

    -c   Output APT sources.list.d config, but do not install

    -a   Install APT sources.list.d config

=== Tarball of Kernel Image and Modules

This is a tarball of the kernel vmlinuz image and all the modules from
`lib/modules/<kernel-version>`.  This tarball is used by bazel to run
tests using QEMU.

== Install Kernel Packages via APT

The Debian archive created by this build process can be used to
install kernel packages via apt.  To setup the apt repo on a host
(either real hardware or virtual) do this:

- download the deb-artifacts.tar.gz from astore
- untar the archive where you want the repo to live (maybe /usr/local/share/enf/kernel-repo)
- using `sudo` run the install script with the `-a` option

  $ cd /tmp
  $ enkit astore get -a amd64 -u 4w7kpbga283xqeyzqei4rjg4rsgg2jnq kernel/enf/impish-19.19/generic/deb-artifacts.tar.gz
  $ sudo mkdir /usr/share/enf/kernel-generic-repo
  $ cd /usr/share/enf/kernel-generic-repo
  $ sudo tar xf /tmp/deb-artifacts.tar.gz
  $ sudo ./install-5.13.0-19-1-1651796444-gffc1f1c68bba-generic.sh -a
  $ sudo apt update
  $ sudo apt install linux-image-5.13.0-19-1-1651796444-gffc1f1c68bba-generic

== Script Details

The main script shells out to a number of helper scripts to handle the
individual steps of the build and release process.

=== `init-build.sh`

This script initializes the scratch build build directory, clones the
kernel repo, and checks out the specified branch.

=== `build-debs.sh`

This script compiles the specified Linux kernel branch and generates
Debian .deb packages for all specified kernel flavours.

A kernel flavour is a particular kernel configuration for an
architecture.  Currently two flavours are supported for amd64:

- generic -- This is a full kernel configuration, suitable for
  installing a real metal server.

=== `repo-deb.sh`

This script creates a portable Debian APT repository for each kernel
flavour.  This APT repo contains all the .deb files generated by
`build-deb.sh`.

=== `archive-bazel-deb.sh`

This script creates a bazel ready tarball of kernel header files for
building amd64 kernel modules for each flavour.  This tarball also
includes an `install` script that bazel executes when unpacking the
tarball.

=== `archive-deb.sh`

This script creates a tarball of a Debian APT repo containing
kernel .deb packages for each flavour.  This repo can be used to
provision real hardware machines or virtual machines.

The install script requires one of the following arguments:

    -c   Output APT sources.list.d config, but do not install

    -a   Install APT sources.list.d config

=== `upload-deb.sh`

This script uploads the amd64 Debian tarballs to astore.

For the bazel header file tarball, the URL is marked as "public",
because bazel requires that.

The URL for the Debian APT repo archive is marked as private in
astore.
