# enkit/allocation_manager/proto/config.proto::Config
server {
  queue_refresh_duration_seconds: 15
  allocation_refresh_duration_seconds: 30
  janitor_interval_seconds: 1
  adoption_duration_seconds: 45
}

units {
topology: {
  name: "a"
  config: "a"
  }
}
units {
topology: {
  name: "b"
  config: "b"
  }
}
