#!/bin/bash
#
# gee: git enabled enfabrication.
#
# A wrapper for our standard git workflow.
#
# A few features:
# 
# * We always use "worktree" -- that is, every branch gets a unique
#   directory in the user's home directory.  (At the moment, this costs
#   about 0.2GB for each branch, which feels cheap.)
#
# * "gee submit" always pushes changes to github so that users will
#   have a backup of their work.  Also, nothing special has to be done
#   to update an outstanding PR.
#
# * Enforce an "ssh"-authenticated workflow.  TODO(jonathan): implement.
#
# workflow:
#   gee init  # only do this once, per repo, ever.
#   gee mkbr # make a new feature branch
#   gee commit  # commit changes
#   gee update  # merge upstream changes
#   gee squash # Squash all changes to a single commit.
#   gee mail  # send a pr request
#   gee commit # update that pr request (again)
#   gee submit  # merge that pr request
#   gee cleanup  # prune branches without local changes.
#
# Additionally, we want the ability to chain feature branches that build
# on one another, and we want "gee update" to recursively traverse chains
# of branches.  A user should be able to send branch "feature1" off for
# review and immediately start work on it's descendant, "feature2" while
# "feature1" is undergoing review.
#
# Enable "worktree" model by default: every branch gets it's own worktree
# under a standard directory tree structure.  Directory name is always
# "<REPO>/branches/<branch>".
#
# Branches:
#    upstream: the original repo we have forked (enfabrica/$REPO)
#              we issue pull requests to this repo, and we integrate
#              changes from here.
#    origin:   the user's forked repo ($GHUSER/$REPO)
#              we pull and push to this repo.
#    upstream/master: top of tree
#    origin/master: user's top-of-tree with no local changes,
#        updated periodically from upstream/master.
#    master: local repo top of tree, no local changes,
#        updated periodically from upstream/master.
#    $feature: fork of master (or other $feature), contains
#        local changes.  May have 0 or 1 PRs associated with it.
#
# All work is done in $feature, and this script automates maintenance of
# the other repos.
#
# TODO(jonathan): Bash implementation is a prototype.  rewrite in golang.

set -e

GIT=/usr/bin/git
GH=/usr/bin/gh
GHUSER="${GHUSER-:$USER-enf}"
SSH="${SSH-:1}"  # enable ssh access by default?
VERBOSE="${VERBOSE:-1}"
DRYRUN="${DRYRUN:-0}"
REPO="${REPO:-}"
declare -a HELP=()

if [[ -z "${REPO}" ]]; then
  # Examine the directory to see if we're in a repo already.
  if [[ "${PWD}" =~ ^${HOME}/([a-z0-9_-]+)/branches/([a-z0-9_-]+) ]]; then
    REPO="${BASH_REMATCH[1]}"
  fi
fi

# If all else fails, default to internal
if [[ -z "${REPO}" ]]; then
  REPO=internal
fi

BRANCHES_DIR="${HOME}/${REPO}/branches/"

function _startup_checks() {
  if [[ ! -x "${GIT}" ]]; then
    _die "${GIT} is not installed."
  fi
  if [[ ! -x "${GH}" ]]; then
    _die "${GH} is not installed."
  fi
}

function _get_parent_branch() {
  # Return the name of the branch that contains the nearest
  # commit to my current commit, that is not in my current
  # branch?
  #
  # TODO(jonathan): maybe just store this as metadata.
  local CURRENT_BRANCH PARENT
  CURRENT_BRANCH="$("${GIT}" branch --show-current)"
  PARENT="$(git show-branch | sed "s/].*//" | grep "\*" \
    | grep -v "${CURRENT_BRANCH}" | head -n1 \
    | perl -pe 'm/\[(.*?)(\^\d+)?(~\d+)?$/; $_ = $1;')"
  if [[ -z "${PARENT}" ]]; then
    echo "master"
  else
    echo "${PARENT}"
  fi
}

function _get_branch_directory() {
  # Return the root directory of a git branch
  local BRANCH_NAME BRDIR
  BRANCH_NAME="$1"
  if [[ -z "${BRANCH_NAME}" ]]; then
    BRANCH_NAME="$("${GIT}" branch --show-current)"
  fi
  BRDIR="$("${GIT}" worktree list \
    | grep -w "\[${BRANCH_NAME}\]" \
    | awk '{print $1}' )"
  if [[ -z "${BRDIR}" ]]; then
    _die "_get_branch_directory failed for ${BRANCH_NAME}"
  fi
  echo "${BRDIR}"
}

function _confirm_or_exit() {
  local _PROMPT RESP
  _PROMPT="$*"
  if [[ -z "${_PROMPT}" ]]; then
    _PROMPT="Confirm? (y/N)  "
  fi
  read -rp "${_PROMPT}" RESP
  case "${RESP}" in
    [Yy]*) ;;
    *) echo "Aborting."
       exit 1
       ;;
  esac
}

function _die() {
  echo >&2 "FATAL: $*"
  if [[ -z "${NOSTACK}" ]]; then
    echo >&2 "Stack trace:"
    local i
    i=0
    while caller "${i}"; do
      (( i++ ))
    done
  fi
  exit 1
}

function _cmd() {
  if [[ $DRYRUN -eq 0 ]]; then
    if [[ $VERBOSE -gt 0 ]]; then
      echo -ne "CMD: "
      printf " %q" "$@"
      printf "\n"
    fi
    set +e
    "$@"
    RC=$?
    if [[ "$RC" -ne 0 ]]; then
      _die "Command failed with exit code ${RC}"
    fi
    set -e
    return $RC
  else
    echo -n "DRYRUN: "
    printf " %q" "$@"
    printf "\n"
  fi
}

function _gh() {
  _cmd "${GH}" "$@"
}

function _git() {
  _cmd "${GIT}" "$@"
}

function _install_gh_tool() {
  # If your dev image is missing the github-cli tool, this should install it.
  local KRFILE; KRFILE="/usr/share/keyrings/githubcli-archive-keyring.gpg"
  /usr/bin/curl -fsSL \
    https://cli.github.com/packages/githubcli-archive-keyring.gpg \
    | sudo /usr/bin/apt-key --keyring "${KRFILE}" add -
  echo "deb [arch=amd64 signed-by=${KRFILE}] https://cli.github.com/packages stable main" \
    | sudo /usr/bin/tee /etc/apt/sources.list.d/githubcli-archive.list
  sudo /usr/bin/apt update && sudo /usr/bin/apt install gh
  if [ ! -x ${GH} ]; then
    _die "Could not install gh."
  fi
}

HELP+=("init: initialize a new git workspace.")
function gee__init() {
    # Initialize a new _git workspace.
    # TODO(jonathan): also support ssh
    _cmd mkdir -p "${BRANCHES_DIR}"
    local URL UPSTREAM_URL
    URL="git@github.com:${GHUSER}/${REPO}.git"
    UPSTREAM_URL=git@github.com:enfabrica/"${REPO}.git"
    # TODO(jonathan): also create and push an ssh key if ssh access
    # isn't already enabled.
    _git clone "${URL}" "${BRANCHES_DIR}/master"
    _cmd cd "${BRANCHES_DIR}/master"
    _git remote add upstream "${UPSTREAM_URL}"
    _git remote -v
    echo "Created ${BRANCHES_DIR}/master"
}

HELP+=("make_branch: create a new branch based on the current branch.")
function gee__mkbr() { gee__make_branch "$@"; }
function gee__make_branch() {
  BRNAME="$1"; shift
  local CURRENT_BRANCH
  CURRENT_BRANCH="$("${GIT}" branch --show-current)"
  if [[ -z "${CURRENT_BRANCH}" ]]; then
    _die "Not in a git branch directory."
  fi

  _git worktree add "${BRANCHES_DIR}/${BRNAME}"
  echo "Created ${BRANCHES_DIR}/${BRNAME}"
}

function gee__log() {
  local PARENT_BRANCH CURRENT_BRANCH
  PARENT_BRANCH="$(_get_parent_branch)"
  CURRENT_BRANCH="$("${GIT}" branch --show-current)"
  _git log "${PARENT_BRANCH}..${CURRENT_BRANCH}"
}

HELP+=("squash: Squash all commits in this branch.")
function gee__squash() {
  local PARENT_BRANCH CURRENT_BRANCH MERGE_BASE TMPFILE NUM_COMMITS
  PARENT_BRANCH="$(_get_parent_branch)"
  CURRENT_BRANCH="$("${GIT}" branch --show-current)"
  MERGE_BASE="$("${GIT}" merge-base "${PARENT_BRANCH}" "${CURRENT_BRANCH}")"
  NUM_COMMITS="$("${GIT}" log --oneline "${PARENT_BRANCH}..${CURRENT_BRANCH}" | /usr/bin/wc -l)"
  if [[ "${NUM_COMMITS}" -lt 2 ]]; then
    echo "${NUM_COMMITS} commits outstanding.  Nothing to squash."
    exit 0
  fi
  TMPFILE="$(mktemp)"
  (
    echo "# Comment lines will be removed."
    echo "# One line summary:"
    echo "[REPLACE THIS LINE]"
    echo ""
    echo "# Details:"
    echo ""
    echo "Files:"
    "${GIT}" diff --name-only "${MERGE_BASE}" | sed 's/^/    /'
    echo ""
    echo "# Previous commit messages:"
    echo "#"
    "${GIT}" log --format=medium "${PARENT_BRANCH}..${CURRENT_BRANCH}" | \
      sed 's/^/# /'
    echo ""
  ) >"${TMPFILE}"
  "${EDITOR:-vim}" "${TMPFILE}"
  sed -i "/^#/d" "${TMPFILE}"
  perl -p -i -e 's/(^\s*\n){2,}/\n/gmso' "${TMPFILE}"
  if grep -q "^\[" "${TMPFILE}"; then
    echo "You must replace the summary line.  Aborting."
    echo "Commit message saved here: ${TMPFILE}"
    exit 1
  fi
  head -n 1 "${TMPFILE}"
  _confirm_or_exit "Are you sure you want to squash ${NUM_COMMITS} commits? (y/N)  "

  _git reset --soft "${MERGE_BASE}"
  _git commit -a -F "${TMPFILE}"
  rm "${TMPFILE}"
  _git push origin "+${CURRENT_BRANCH}"  # update remote branch too
  _git log --oneline "${PARENT_BRANCH}..${CURRENT_BRANCH}"
}
  




# oh yeah, this can't work -- reformulate this as an alias.
# HELP+=("change_branch: change to the same relative path in another branch.")
# function gee__chbr() { gee__change_branch "$@"; }
# function gee__change_branch() {
#   BRNAME="$1"; shift
#   local CURRENT_BRANCH
#   CURRENT_BRANCH="$("${GIT}" branch --show-current)"
#   if [[ -z "${CURRENT_BRANCH}" ]]; then
#     echo "ERROR: Not in git branch directory."
#     exit 1
#   fi
#   REL_PATH="$("${GIT}" rev-parse --show-prefix)"
#   cd "${BRANCHES_DIR}/${BRNAME}/${REL_PATH}"
#   pwd
# }

function _checkout_or_die() {
  # we want to check out a branch.  Maybe there is already a
  # worktree.  Maybe we need to create a worktree.  Let's do
  # whatever is necessary.
  local BRNAME BRDIR
  BRNAME="$1"; shift
  # Do we already have a worktree?
  BRDIR="$(_get_branch_directory "${BRNAME}")"
  if [[ -z "${BRANCHES_DIR}" ]]; then
    _git worktree add "${BRANCHES_DIR}/${BRNAME}"
    BRDIR="$(_get_branch_directory "${BRNAME}")"
  fi
  if [[ -z "${BRDIR}" ]]; then
    _die "Could not check out ${BRNAME}"
  fi
}

HELP+=("update: integrate upstream changes into this branch.")
function gee__update() {
  local CURRENT_BRANCH
  CURRENT_BRANCH="$("${GIT}" branch --show-current)"
  if [[ -z "${CURRENT_BRANCH}" ]]; then
    _die "Not in a git branch directory."
  fi
  MASTER_BRANCH="$("${GIT}" worktree list | grep -w \\\[master\\\] | awk '{print $1}' )"
  if [[ -z "${MASTER_BRANCH}" ]]; then
    MASTER_BRANCH="${BRANCHES_DIR}/master"  # default place where master branch should reside.
  fi
  local UNCOMMITTED
  UNCOMMITTED="$("${GIT}" status --short -uall | wc -l)"
  if [[ "${UNCOMMITTED}" -gt 0 ]]; then
    echo "Branch contains ${UNCOMMITTED} uncommitted changes:"
    _git status --short -uall
    echo "Run \"gee commit\" and try again."
    exit 1
  fi
  _git fetch upstream
  _checkout_or_die master
  _git merge upstream/master
  _checkout_or_die "${CURRENT_BRANCH}"
  _git rebase master
  _git pull origin "${CURRENT_BRANCH}"
  _git push origin "${CURRENT_BRANCH}"
}

HELP+=("config: configure _git and _gh tools.")
function gee__config() {
  _gh config "$@"
}

HELP+=("whatsout: list locally changed files in this branch.")
function gee__whatsout() {
  _git diff --name-only master
}

# Report how many commits this branch is ahead/behind master.
function branch_ahead_behind() {
  local branch; branch="$1"
  local remote; remote="$("${GIT}" config branch."${branch}".remote)"
  local obr; obr=""
  if [[ -z "$remote" ]]; then
    obr=master
  else
    local mergebr; mergebr="$("${GIT}" config branch."${branch}".merge | cut -d / -f 3)"
    obr=${remote}/${mergebr}
  fi
  local -a counts
  read -r -a counts < <("${GIT}" rev-list --left-right --count "${branch}...${obr}")
  echo -e "${branch}:\t${counts[0]} ahead, ${counts[1]} behind ${obr}"
}

# Get info about all branches.
HELP+=("lsbranches: list information about each branch.")
function gee__lsb() { gee__lsbranches "$@"; }
function gee__lsbr() { gee__lsbranches "$@"; }
function gee__lsbranches() {
  local -a branches;
  mapfile -t branches < <( "${GIT}" branch --format "%(refname:short)")
  local br
  for br in "${branches[@]}"; do
    branch_ahead_behind "${br}"
  done
}

HELP+=("commit: commit all changes in this branch")
function gee__push() { gee__commit "$@"; }
function gee__commit() {
  local CURRENT_BRANCH
  CURRENT_BRANCH="$("${GIT}" branch --show-current)"
  BRANCH_DIR="$(_get_branch_directory "${CURRENT_BRANCH}")"
  echo "${BRANCH_DIR}" "${HOME}"
  if [[ "${BRANCH_DIR}" != "${HOME}" ]]; then
    _git add --all
  else
    echo "Skipped \"git add --all\" because branch is home dir."
  fi
  NOSTACK=1 _git commit "$@"
  # We always push upstream so that users have a backup in case they lose their
  # laptop:
  _git pull origin "${CURRENT_BRANCH}"
  _git push origin "${CURRENT_BRANCH}"
}

HELP+=("send: Send a PR out for review.")
function gee__mail() { gee__send "$@"; }
function gee__send() {
  if "${GH}" pr view > /dev/null; then
    echo "PR already exists, use \"git commit\" to update."
    _gh pr view
    exit 1
  fi

  local PARENT_BRANCH CURRENT_BRANCH MERGE_BASE NUM_COMMITS
  PARENT_BRANCH="$(_get_parent_branch)"
  CURRENT_BRANCH="$("${GIT}" branch --show-current)"
  MERGE_BASE="$("${GIT}" merge-base "${PARENT_BRANCH}" "${CURRENT_BRANCH}")"

  UNCOMMITTED="$("${GIT}" status --short -uall | wc -l)"
  if [[ "${UNCOMMITTED}" -gt 0 ]]; then
    echo "Branch contains ${UNCOMMITTED} uncommitted changes:"
    _git status --short -uall
    echo "Run \"gee commit\" and try again."
    exit 1
  fi

  NUM_COMMITS="$("${GIT}" log --oneline "${PARENT_BRANCH}..${CURRENT_BRANCH}" | wc -l)"
  if [[ "${NUM_COMMITS}" -eq 0 ]]; then
    echo "No changes in this branch."
    exit 1
  fi
  if [[ "${NUM_COMMITS}" -gt 1 ]]; then
    local YN
    echo "There are ${NUM_COMMITS} commits outstanding."
    read -rp "Do you want to squash before sending this PR? (y/N)  " YN
    if [[ "$YN" =~ ^[yY] ]]; then
      gee__squash
    fi
  fi

  _gh pr create
  # _gh pr checks  # not sure why this is problematic.
  _gh pr view
  echo "Add reviewers."
}
  

function gee__submit() { gee__merge "$@"; }
function gee__merge() {
  _gh pr checks
  _gh pr merge --squash
  _git pull
}

function main() {
  local cmdname="$1"; shift
  if type "gee__${cmdname}" >/dev/null 2>&1; then
    _startup_checks
    "gee__${cmdname}" "$@"
  else
    echo "Unknown command ${cmdname}"
    echo ""
    echo "Commands:"
    for h in "${HELP[@]}"; do
      echo "  $h"
    done
    exit 2
  fi
}

main "$@"
